network:
  version: 2
  ethernets:
    renderer: networkd
    ethernet:
      match:
        name: e*
      dhcp4: true
      dhcp6: false
      set-name: eth0
  wifis:
    renderer: networkd
    wlan0:
      access-points:
        "<REMOVED>":
          password: "<REMOVED>"
      dhcp4: true
      dhcp6: false
      optional: true
      set-name: wlan
